"""
Material Dark Design System for Fetchreel Windows Desktop.
Matching the Android application theme and color tokens.
"""

# Color Palette
DARK_BG = "#0F1117"
DARK_SURFACE = "#161B26"
DARK_CARD = "#1F2937"
DARK_CARD_HOVER = "#273549"
DARK_BORDER = "#374151"

ACCENT_INDIGO = "#6366F1"
ACCENT_INDIGO_HOVER = "#4F46E5"
ACCENT_INDIGO_LIGHT = "#818CF8"
ACCENT_CYAN = "#06B6D4"
ACCENT_CYAN_HOVER = "#0891B2"

TEXT_PRIMARY = "#F9FAFB"
TEXT_SECONDARY = "#9CA3AF"
TEXT_MUTED = "#6B7280"

SUCCESS_GREEN = "#10B981"
SUCCESS_GREEN_HOVER = "#059669"
ERROR_RED = "#EF4444"
ERROR_RED_HOVER = "#DC2626"
WARNING_AMBER = "#F59E0B"

# Font configurations
FONT_FAMILY = "Segoe UI"
FONT_TITLE = (FONT_FAMILY, 20, "bold")
FONT_SUBTITLE = (FONT_FAMILY, 15, "bold")
FONT_BODY = (FONT_FAMILY, 13, "normal")
FONT_BODY_BOLD = (FONT_FAMILY, 13, "bold")
FONT_SMALL = (FONT_FAMILY, 11, "normal")
FONT_SMALL_BOLD = (FONT_FAMILY, 11, "bold")
FONT_BADGE = (FONT_FAMILY, 10, "bold")
